export const INJECTION_TOKENS = {
  // Repositories
  USER_REPOSITORY: Symbol('USER_REPOSITORY'),
  STORE_REPOSITORY: Symbol('STORE_REPOSITORY'),
  PRODUCT_REPOSITORY: Symbol('PRODUCT_REPOSITORY'),
  VARIANT_REPOSITORY: Symbol('VARIANT_REPOSITORY'),
  CATEGORY_REPOSITORY: Symbol('CATEGORY_REPOSITORY'),
  ORDER_REPOSITORY: Symbol('ORDER_REPOSITORY'),
  ANALYTICS_REPOSITORY: Symbol('ANALYTICS_REPOSITORY'),
  VISITOR_REPOSITORY: Symbol('VISITOR_REPOSITORY'),
  PAYMENT_REPORT_REPOSITORY: Symbol('PAYMENT_REPORT_REPOSITORY'),

  // Services
  STORAGE_SERVICE: Symbol('STORAGE_SERVICE'),
  EMAIL_SERVICE: Symbol('EMAIL_SERVICE'),
  PAYMENT_SERVICE: Symbol('PAYMENT_SERVICE'),
  CACHE_SERVICE: Symbol('CACHE_SERVICE'),
} as const;
