export const INJECTION_TOKENS = {
  // Repositories
  USER_REPOSITORY: Symbol('USER_REPOSITORY'),
  STORE_REPOSITORY: Symbol('STORE_REPOSITORY'),
  PRODUCT_REPOSITORY: Symbol('PRODUCT_REPOSITORY'),
  VARIANT_REPOSITORY: Symbol('VARIANT_REPOSITORY'),
  CATEGORY_REPOSITORY: Symbol('CATEGORY_REPOSITORY'),
  ORDER_REPOSITORY: Symbol('ORDER_REPOSITORY'),
  ANALYTICS_REPOSITORY: Symbol('ANALYTICS_REPOSITORY'),
  VISITOR_REPOSITORY: Symbol('VISITOR_REPOSITORY'),
  PAYMENT_REPORT_REPOSITORY: Symbol('PAYMENT_REPORT_REPOSITORY'),
  LANDING_VISITOR_REPOSITORY: Symbol('LANDING_VISITOR_REPOSITORY'),
  PAYMENT_METHOD_REPOSITORY: Symbol('PAYMENT_METHOD_REPOSITORY'),
  STORE_HOURS_REPOSITORY: Symbol('STORE_HOURS_REPOSITORY'),
  STORE_VIEW_REPOSITORY: Symbol('STORE_VIEW_REPOSITORY'),
  SLUG_MISS_REPOSITORY: Symbol('SLUG_MISS_REPOSITORY'),
  RATE_REPOSITORY: Symbol('RATE_REPOSITORY'),
  STORE_SOCIAL_LINK_REPOSITORY: Symbol('STORE_SOCIAL_LINK_REPOSITORY'),
  STORE_DOMAIN_REPOSITORY: Symbol('STORE_DOMAIN_REPOSITORY'),
  DNS_TXT_RESOLVER: Symbol('DNS_TXT_RESOLVER'),

  // Services
  STORAGE_SERVICE: Symbol('STORAGE_SERVICE'),
  EMAIL_SERVICE: Symbol('EMAIL_SERVICE'),
  PAYMENT_SERVICE: Symbol('PAYMENT_SERVICE'),
  CACHE_SERVICE: Symbol('CACHE_SERVICE'),
  OG_IMAGE_CACHE: Symbol('OG_IMAGE_CACHE'),
} as const;
